#!/usr/bin/env python3

from struct import pack
from subprocess import check_call, check_output
from sys import argv, stdout

sz = check_output(['identify', '-format', '%w %h', argv[1]]).decode()
tokens = sz.split()
width, height = int(tokens[0]), int(tokens[1])

stdout.buffer.write(b'farbfeld')
stdout.buffer.write(pack('>L', width))
stdout.buffer.write(pack('>L', height))
stdout.flush()

check_call(['convert', argv[1], '-depth', '16', '-endian', 'MSB', 'RGBA:-'])
